# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: idm.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'idm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tidm.proto\x12\x04grpc\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"W\n\x15ValidateTokenResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x0e\n\x06userId\x18\x04 \x01(\t2W\n\x0b\x41uthService\x12H\n\rValidateToken\x12\x1a.grpc.ValidateTokenRequest\x1a\x1b.grpc.ValidateTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'idm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATETOKENREQUEST']._serialized_start=19
  _globals['_VALIDATETOKENREQUEST']._serialized_end=56
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=58
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=145
  _globals['_AUTHSERVICE']._serialized_start=147
  _globals['_AUTHSERVICE']._serialized_end=234
# @@protoc_insertion_point(module_scope)
